### ISSUE TITLE
Pop!_OS version history

### ISSUE THREAD

**Issue by FlorianBreitenlacher** [pop-os/website#46]
I needed to download an older version of Pop!_OS, because I have problems with the version 21.10. Since there is no official version history is very inconvenient to get an older version.

Currently we can download older version from the https://pop-iso.sfo2.cdn.digitaloceanspaces.com/ server.

21.04 and 21.10 are missing in the xml file but are still downloadable when you know the right key. This might be a separate issue!

Just because you want to have an older version, having to read the xml file is not very user friendly. A version history would make it easier to download an older version.

**Comment by ahoneybun** [comment]
The main issue here is that 21.04 support will end on 1/22/22 so it's not ideal for a user to install a soon to be unsupported OS.

**Comment by FlorianBreitenlacher** [comment]
I am aware of this, but whats the point in having a xml file with all versions and 'hide' it from the user? There are a few use cases where you want or need an older version. A warning message that these are unsupported OS images should be enough.

**Comment by btkostner** [comment]
This domain is not meant to be user facing. The XML file isn't something we control or even use, it's because the domain points to a standard S3 compatible bucket hosted on Digital Ocean that we use for storing the Pop!_OS ISOs.

Considering we use an API server for getting the latest Pop!_OS ISO for the website, including version history would involve changing the whole build process. Also note that _all_ built ISOs are pushed to that bucket, so not all of them are intended to be released, especially the earlier builds.

**Comment by FlorianBreitenlacher** [comment]
Thank you for explaining it to me.
