### ISSUE TITLE
https://account.system76.com/login - trying to login with github fails

### ISSUE THREAD

**Issue by matkoniecz** [pop-os/website#72]
https://account.system76.com/login

![screen01](https://user-images.githubusercontent.com/899988/199934973-8b17c7a6-83a8-48ae-a369-d5ab0b36064a.png)

**Comment by jacobgkau** [comment]
This repository is only for the Pop!_OS subdomain (https://pop.system76.com/) and does not include authentication, but I can forward this along to the web team. Do you also have an email-based account, or are you attempting to sign in with GitHub for the first time?

The System76 support team can also be reached at (720) 226-9269 and can look up accounts, orders, etc. while on the phone.

**Comment by matkoniecz** [comment]
> or are you attempting to sign in for the first time with GitHub?

this one

some other place on website was mentioning it as a primary contact point if anything goes wrong (I later found Github issue repository)

**Comment by matkoniecz** [comment]
https://system76.com/contact -> https://support.system76.com/

**Comment by jacobgkau** [comment]
> some other place on Pop OS website was mentioning it as a primary contact point if anything goes wrong with pop os (I later found Github issue repository)
> 
> note that I do not have any support contract at all

I'm not sure exactly what you're saying, but anyone who owns a System76 computer (first-hand or second-hand) can create a support ticket after logging in. You also need to log in (or register) in order to make a purchase, of course.

**Comment by jacobgkau** [comment]
What web browser are you using, and does it have any extensions or ad blockers installed? Also, does the error message in your screenshot appear before or after you are redirected to GitHub to sign in and/or grant permission for the System76 website to read from your GitHub account?

**Comment by matkoniecz** [comment]
> Also, does the error message in your screenshot appear before or after you are redirected to GitHub to sign in and/or grant permission for the System76 website to read from your GitHub account?

after - https://github.com/settings/applications lists

![screen](https://user-images.githubusercontent.com/899988/200106773-b83958bf-0721-44cf-b495-0dcd4dfbc30a.png)

> I'm not sure exactly what you're saying, but anyone who owns a System76 computer (first-hand or second-hand) can create a support ticket after logging in. You also need to log in (or register) in order to make a purchase, of course.

I never bought or owned System76 computer (I am person interested in pop!OS as a replacement for Ubuntu)

**Comment by matkoniecz** [comment]
https://en.wikipedia.org/wiki/Pop!_OS still links https://pop.system76.com/ as the official homepage of this OS (maybe that should be changed) with https://support.system76.com/ linked in the footer

**Comment by jacobgkau** [comment]
> https://en.wikipedia.org/wiki/Pop!_OS still links https://pop.system76.com/ as the official homepage of this OS (maybe that should be changed)

No, pop.system76.com is the homepage for Pop!_OS specifically.

> maybe info at https://support.system76.com/ that it is solely for people who bought hardware would be a good idea

There is info there for hardware owners, such as https://support.system76.com/articles/system-firmware and https://support.system76.com/articles/system76-driver. If you mean removing info about the software from the support website, that would be a disservice to our customers who bought hardware to use with our software.

There was a project to create a separate documentation website specifically for Pop!_OS (and not hardware), although it had to be put on hold due to internal priorities: https://github.com/pop-os/docs It may see a resurgence when COSMIC Epoch is closer to release.

> before this issue I was aware of Pop!OS but not of related hardware

We do have this section on the pop.system76.com page:

![image](https://github.com/pop-os/website/assets/7199422/0ff7294f-36d3-4d6a-8fb3-0be69190f808)

Thanks for the feedback regarding the website organization, it's something that's considered from time to time. This issue was about GitHub login-- are you still unable to log in? We haven't had any others reporting issues with this recently, from what I can see (the only reports I found were from 2021 and prior.)

I believe we can unlink the account from GitHub so you can submit a password reset request to log in normally, if you provide your email address (or reach out to our sales or support teams to provide it.)

**Comment by matkoniecz** [comment]
> This issue was about GitHub login-- are you still unable to log in?

I can't.

But from what I understood it seems that only people with already existing accounts who ordered pop hardware were supposed to be able to log in. (maybe I misunderstood)

**Comment by jacobgkau** [comment]
Anyone is supposed to be able to log in in order to purchase (and later get support for) System76 hardware.

If you don't want to provide an email address or contact one of our teams privately to share an email address so we can look into the issue further, then I'm afraid there's not much we can do to troubleshoot.

**Comment by matkoniecz** [comment]
Is it happening with other GitHub accounts without an existing account on system76?

**Comment by ElmeriVincent** [comment]
> Is it happening with other GitHub accounts without an existing account on system76?

No, tried it and it worked perfectly. If you are 

> If you don't want to provide an email address or contact one of our teams privately to share an email address so we can look into the issue further, then I'm afraid there's not much we can do to troubleshoot.

Do what Jacob said, it will help.

**Comment by jacobgkau** [comment]
@ElmeriVincent Thank you for confirming you're able to log in.

@matkoniecz I'm going to go ahead and close this issue since GitHub login seems to be working for other users, and because this repo is only for the Pop!_OS page. Once again, we want you to be able to log in (creating an account is required to purchase hardware, after all), so please feel free to leave another comment here with your email address, or call in to one of our teams using the phone number on the support and contact pages. Someone can then take a look at what's going on with your email address/GitHub account link specifically.
